# reduced_column_names = ['Is_a_suspect_arrested',
#  'Year_of_an_incident',
#  'Duration_of_the_observed_mintues',
#  'Day_of_the_week',
#  'Month_of_the_year',
#  'Stop_duration_minutes',
#  'Suspect_height',
#  'Suspect_weight',
#  'Suspect_age',
#  'Time_of_incident',
#  'Stop_location_x',
#  'Stop_location_y']

# arrest_reduced_column_names = ['Is suspect searched?',
#  'Is weapon found?',
#  'Suspect age?',
#  'Stop duration minutes?',
#  'Month of an incident?',
#  'Day of an incident?',
#  'Duration of the observed mintues?',
#  'Is suspect frisked?',
#  'Year of an incident?',
#  'Did officer explianed stop?',
#  'Is officer in uniform?',
#  'Is summon issued?']

reduced_column_names = ['SUSPECT_ARRESTED_FLAG',
 'YEAR',
 'OBSERVED_DURATION_MINUTES',
 'DAY',
 'MONTH',
 'STOP_DURATION_MINUTES',
 'SUSPECT_HEIGHT',
 'SUSPECT_WEIGHT',
 'SUSPECT_REPORTED_AGE',
 'SECONDS',
 'STOP_LOCATION_X',
 'STOP_LOCATION_Y']

arrest_reduced_column_names = ['SEARCHED_FLAG',
 'WEAPON_FOUND_FLAG',
 'SUSPECT_REPORTED_AGE',
 'STOP_DURATION_MINUTES',
 'MONTH',
 'DAY',
 'OBSERVED_DURATION_MINUTES',
 'FRISKED_FLAG',
 'YEAR',
 'OFFICER_EXPLAINED_STOP_FLAG',
 'OFFICER_IN_UNIFORM_FLAG',
 'SUMMONS_ISSUED_FLAG']