-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- Link to schema: https://app.quickdatabasediagrams.com/#/d/a4u9hc
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.

-- Modify this code to update the DB schema diagram.
-- To reset the sample schema, replace everything with
-- two dots ('..' - without quotes).

CREATE TABLE "sqf_merged_data" (
    "id" int   NOT NULL,
    "year" int   NOT NULL,
    "month" varchar   NOT NULL,
    "day" varchar   NOT NULL,
    "stop_was_initiated" varchar   NOT NULL,
    "record_status_code" varchar   NOT NULL,
    "issuing_officer_rank" varchar   NOT NULL,
    "issuing_officer_command_code" int   NOT NULL,
    "supervising_officer_rank" varchar   NOT NULL,
    "supervising_officer_command_code" int   NOT NULL,
    "location_in_out_code" varchar   NOT NULL,
    "jurisdiction_code" varchar   NOT NULL,
    "jurisdiction_description" varchar   NOT NULL,
    "observed_duration_minutes" int   NOT NULL,
    "suspected_crime_description" varchar   NOT NULL,
    "stop_duration_minutes" int   NOT NULL,
    "officer_explained_stop_flag" varchar   NOT NULL,
    "officer_not_explained_stop_description" varchar   NOT NULL,
    "other_person_stopped_flag" varchar   NOT NULL,
    "suspect_arrested_flag" varchar   NOT NULL,
    "suspect_arrest_offense" varchar   NOT NULL,
    "summons_issued_flag" varchar   NOT NULL,
    "summons_offense_description" varchar   NOT NULL,
    "officer_in_uniform_flag" varchar   NOT NULL,
    "id_card_identifies_officer_flag" varchar   NOT NULL,
    "shield_identifies_officer_flag" varchar   NOT NULL,
    "verbal_identifies_officer_flag" varchar   NOT NULL,
    "frisked_flag" varchar   NOT NULL,
    "searched_flag" varchar   NOT NULL,
    "ask_for_consent_flg" varchar   NOT NULL,
    "consent_given_flg" varchar   NOT NULL,
    "other_contraband_flag" varchar   NOT NULL,
    "firearm_flag" varchar   NOT NULL,
    "knife_cutter_flag" varchar   NOT NULL,
    "other_weapon_flag" varchar   NOT NULL,
    "weapon_found_flag" varchar   NOT NULL,
    "physical_force_cew_flag" varchar   NOT NULL,
    "physical_force_draw_point_firearm_flag" varchar   NOT NULL,
    "physical_force_handcuff_suspect_flag" varchar   NOT NULL,
    "physical_force_oc_spray_used_flag" varchar   NOT NULL,
    "physical_force_other_flag" varchar   NOT NULL,
    "physical_force_restraint_used_flag" varchar   NOT NULL,
    "physical_force_verbal_instruction_flag" varchar   NOT NULL,
    "physical_force_weapon_impact_flag" varchar   NOT NULL,
    "backround_circumstances_violent_crime_flag" varchar   NOT NULL,
    "backround_circumstances_suspect_known_to_carry_weapon_flag" varchar   NOT NULL,
    "suspects_actions_casing_flag" varchar   NOT NULL,
    "suspects_actions_concealed_possession_weapon_flag" varchar   NOT NULL,
    "suspects_actions_decription_flag" varchar   NOT NULL,
    "suspects_actions_drug_transactions_flag" varchar   NOT NULL,
    "suspects_actions_identify_crime_pattern_flag" varchar   NOT NULL,
    "suspects_actions_lookout_flag" varchar   NOT NULL,
    "suspects_actions_other_flag" varchar   NOT NULL,
    "suspects_actions_proximity_to_scene_flag" varchar   NOT NULL,
    "search_basis_admission_flag" varchar   NOT NULL,
    "search_basis_consent_flag" varchar   NOT NULL,
    "search_basis_hard_object_flag" varchar   NOT NULL,
    "search_basis_incidental_to_arrest_flag" varchar   NOT NULL,
    "search_basis_other_flag" varchar   NOT NULL,
    "search_basis_outline_flag" varchar   NOT NULL,
    "demeanor_code" varchar   NOT NULL,
    "demeanor_of_person_stopped" varchar   NOT NULL,
    "suspect_reported_age" varchar   NOT NULL,
    "suspect_sex" varchar   NOT NULL,
    "suspect_race_description" varchar   NOT NULL,
    "suspect_height" varchar   NOT NULL,
    "suspect_weight" varchar   NOT NULL,
    "suspect_body_build_type" varchar   NOT NULL,
    "suspect_eye_color" varchar   NOT NULL,
    "suspect_hair_color" varchar   NOT NULL,
    "suspect_other_description" varchar   NOT NULL,
    "stop_location_precinct" varchar   NOT NULL,
    "stop_location_sector_code" varchar   NOT NULL,
    "stop_location_apartment" varchar   NOT NULL,
    "stop_location_full_address" varchar   NOT NULL,
    "stop_location_street_name" varchar   NOT NULL,
    "stop_location_x" varchar   NOT NULL,
    "stop_location_y" varchar   NOT NULL,
    "stop_location_zip_code" varchar   NOT NULL,
    "stop_location_patrol_boro_name" varchar   NOT NULL,
    "stop_location_boro_name" varchar   NOT NULL,
    "stop_frisk_id" int   NOT NULL,
    "supervising_action_corresponding_activity_log_entry_reviewed" varchar   NOT NULL,
    "stop_location_premises_name" varchar   NOT NULL,
    "seconds" int   NOT NULL,
    CONSTRAINT "pk_sqf_merged_data" PRIMARY KEY (
        "id"
     )
);

CREATE TABLE "sqf_2020_data" (
    "id" int   NOT NULL,
    "year" int   NOT NULL,
    "month" varchar   NOT NULL,
    "day" varchar   NOT NULL,
    "stop_was_initiated" varchar   NOT NULL,
    "record_status_code" varchar   NOT NULL,
    "issuing_officer_rank" varchar   NOT NULL,
    "issuing_officer_command_code" int   NOT NULL,
    "supervising_officer_rank" varchar   NOT NULL,
    "supervising_officer_command_code" int   NOT NULL,
    "location_in_out_code" varchar   NOT NULL,
    "jurisdiction_code" varchar   NOT NULL,
    "jurisdiction_description" varchar   NOT NULL,
    "observed_duration_minutes" int   NOT NULL,
    "suspected_crime_description" varchar   NOT NULL,
    "stop_duration_minutes" int   NOT NULL,
    "officer_explained_stop_flag" varchar   NOT NULL,
    "officer_not_explained_stop_description" varchar   NOT NULL,
    "other_person_stopped_flag" varchar   NOT NULL,
    "suspect_arrested_flag" varchar   NOT NULL,
    "suspect_arrest_offense" varchar   NOT NULL,
    "summons_issued_flag" varchar   NOT NULL,
    "summons_offense_description" varchar   NOT NULL,
    "officer_in_uniform_flag" varchar   NOT NULL,
    "id_card_identifies_officer_flag" varchar   NOT NULL,
    "shield_identifies_officer_flag" varchar   NOT NULL,
    "verbal_identifies_officer_flag" varchar   NOT NULL,
    "frisked_flag" varchar   NOT NULL,
    "searched_flag" varchar   NOT NULL,
    "ask_for_consent_flg" varchar   NOT NULL,
    "consent_given_flg" varchar   NOT NULL,
    "other_contraband_flag" varchar   NOT NULL,
    "firearm_flag" varchar   NOT NULL,
    "knife_cutter_flag" varchar   NOT NULL,
    "other_weapon_flag" varchar   NOT NULL,
    "weapon_found_flag" varchar   NOT NULL,
    "physical_force_cew_flag" varchar   NOT NULL,
    "physical_force_draw_point_firearm_flag" varchar   NOT NULL,
    "physical_force_handcuff_suspect_flag" varchar   NOT NULL,
    "physical_force_oc_spray_used_flag" varchar   NOT NULL,
    "physical_force_other_flag" varchar   NOT NULL,
    "physical_force_restraint_used_flag" varchar   NOT NULL,
    "physical_force_verbal_instruction_flag" varchar   NOT NULL,
    "physical_force_weapon_impact_flag" varchar   NOT NULL,
    "backround_circumstances_violent_crime_flag" varchar   NOT NULL,
    "backround_circumstances_suspect_known_to_carry_weapon_flag" varchar   NOT NULL,
    "suspects_actions_casing_flag" varchar   NOT NULL,
    "suspects_actions_concealed_possession_weapon_flag" varchar   NOT NULL,
    "suspects_actions_decription_flag" varchar   NOT NULL,
    "suspects_actions_drug_transactions_flag" varchar   NOT NULL,
    "suspects_actions_identify_crime_pattern_flag" varchar   NOT NULL,
    "suspects_actions_lookout_flag" varchar   NOT NULL,
    "suspects_actions_other_flag" varchar   NOT NULL,
    "suspects_actions_proximity_to_scene_flag" varchar   NOT NULL,
    "search_basis_admission_flag" varchar   NOT NULL,
    "search_basis_consent_flag" varchar   NOT NULL,
    "search_basis_hard_varchar_flag" varchar   NOT NULL,
    "search_basis_incidental_to_arrest_flag" varchar   NOT NULL,
    "search_basis_other_flag" varchar   NOT NULL,
    "search_basis_outline_flag" varchar   NOT NULL,
    "demeanor_code" varchar   NOT NULL,
    "demeanor_of_person_stopped" varchar   NOT NULL,
    "suspect_reported_age" varchar   NOT NULL,
    "suspect_sex" varchar   NOT NULL,
    "suspect_race_description" varchar   NOT NULL,
    "suspect_height" varchar   NOT NULL,
    "suspect_weight" varchar   NOT NULL,
    "suspect_body_build_type" varchar   NOT NULL,
    "suspect_eye_color" varchar   NOT NULL,
    "suspect_hair_color" varchar   NOT NULL,
    "suspect_other_description" varchar   NOT NULL,
    "stop_location_precinct" int   NOT NULL,
    "stop_location_sector_code" varchar   NOT NULL,
    "stop_location_apartment" varchar   NOT NULL,
    "stop_location_full_address" varchar   NOT NULL,
    "stop_location_street_name" varchar   NOT NULL,
    "stop_location_x" int   NOT NULL,
    "stop_location_y" int   NOT NULL,
    "stop_location_zip_code" varchar   NOT NULL,
    "stop_location_patrol_boro_name" varchar   NOT NULL,
    "stop_location_boro_name" varchar   NOT NULL,
    "seconds" int   NOT NULL,
    CONSTRAINT "pk_sqf_2020_data" PRIMARY KEY (
        "id"
     )
);

